mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tim.entity


spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost/tbshop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT&useSSL=false
        username: root
        password: 123123
        driverClassName: com.mysql.cj.jdbc.Driver

        initialSize: 10
        maxActive: 100
        minIdle: 30
        maxWait: 60000
        defaultAutoCommit: false
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        #validationQuery=SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

server:
  port: 8087
  servlet:
    context-path: /
  address: 127.0.0.1

logging:
  config: classpath:logback.xml



