mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tim.entity


spring:
  datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost/tbshop?useUnicode=true&amp;characterEncoding=utf8&useSSL=true
        username: root
        password: root
        driverClassName: com.mysql.jdbc.Driver

        initialSize: 10
        maxActive: 100
        minIdle: 30
        maxWait: 60000
        defaultAutoCommit: false
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        #validationQuery=SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

server:
  port: 8087
  servlet:
    context-path: /
  address: 127.0.0.1

logging:
  level:
    root: info
    org.openqa.selenium : error


